#11
dyeimys/events pull request #38
Opened 2023-03-26 17:34 UTC by gsantosdev

2023-03-26 17:35 UTC, gsantosdev commented on src/main/kotlin/br/dfranco/learn/events/application/usecases/CreateLocationUseCase.kt
> +}
Talvez mandar isso pra uma service utilitária no futuro

2023-03-27 01:22 UTC, dyeimys requested changes

2023-03-27 01:22 UTC, dyeimys commented on src/test/kotlin/br/dfranco/learn/events/application/usecases/CreateLocationUseCaseTest.kt
> +class CreateLocationUseCaseTest {
Como a regra de endereço está vinculado ao nome e endereço, vale a pena fazer os testes validando esses pontos. 

Cenários:
Nome e endereço igual 
Apenas nome igual 
Apenas endereço igual. 
Porém como essa regra ficou na busca no banco pode fazer o teste via repository e ainda colocando constraint

2023-03-30 17:52 UTC, gsantosdev commented on src/test/kotlin/br/dfranco/learn/events/application/usecases/CreateLocationUseCaseTest.kt
> +class CreateLocationUseCaseTest {
Fazer um teste de repository numa classe separada?

2023-03-30 17:56 UTC, dyeimys commented on src/test/kotlin/br/dfranco/learn/events/application/usecases/CreateLocationUseCaseTest.kt
> +class CreateLocationUseCaseTest {
Sim, testes de repositoy. 
Só para amarrar a regra. 

https://github.com/dyeimys/events/blob/main/src/test/kotlin/br/dfranco/learn/events/infrastructure/persistence/EventRepositoryTest.kt

O testes de repository é até bom caso queria deixar testado as constraints e afins

2023-03-30 19:42 UTC, gsantosdev commented on src/test/kotlin/br/dfranco/learn/events/application/usecases/CreateLocationUseCaseTest.kt
> +class CreateLocationUseCaseTest {
https://github.com/dyeimys/events/issues/11 [- Create Location Repository Tests](https://github.com/dyeimys/events/pull/38/commits/23b3dad1a08f663b8e26da90567454d0131168e4)

2023-03-30 19:44 UTC, dyeimys approved these changes

2023-03-30 19:44 UTC, merged

2023-03-30 21:11 UTC, gsantosdev commented on src/test/kotlin/br/dfranco/learn/events/application/usecases/CreateLocationUseCaseTest.kt
> +class CreateLocationUseCaseTest {
https://github.com/dyeimys/events/issues/11 [- Create Location Repository Tests](https://github.com/dyeimys/events/pull/38/commits/23b3dad1a08f663b8e26da90567454d0131168e4)